#!/bin/bash
#uso: ./nmjs-easycap <cameras> <shm_dir>
#ex.: ./nmjs-easycap 17:1,18:2 /dev/shm/

arr=()
i=1
cam=`echo $1 | cut -d , -f $i`
while [ -n "$cam" ]; do
  arr+=($cam)
  (( i++ ))
  cam=`echo $1 | cut -d , -f $i`
done

buf=1
while :
do
  for c in ${arr[@]}
  do
    #echo $c # or do whatever with individual element of the array
    cam=`echo $c | cut -d : -f 1`
    inp=`echo $c | cut -d : -f 2`
    echo "$cam = $inp ($buf)"
    #somagic-capture -n --sync=1 --iso-transfers=20 -i $inp -f 4 | ffmpeg -f rawvideo -pix_fmt uyvy422 -s 720x480 -r ntsc -an -i pipe: -vf yadif -vtag 2vuy -aspect 1.77 -b:v 4000k -f image2 -pix_fmt bgr24 -s 320x240 -y -updatefirst 1 $2$cam-$buf.raw
    sleep .6
  done
  (( buf++ ))
  if [ "$buf" -gt 4 ]; then
    buf=1
  fi
done
