#!/bin/bash
#uso: ./nmjs-easycap <cameras> <shm_dir> <frames_to_read>
#ex.: ./nmjs-easycap 17:1,18:2 /dev/shm/ 4

arr=()
i=1
cam=`echo $1 | cut -d , -f $i`
while [ -n "$cam" ]; do
  arr+=($cam)
  (( i++ ))
  cam=`echo $1 | cut -d , -f $i`
done

ff=$3
(( ff-- ))
buf=1

while :
do
  for c in ${arr[@]}
  do
    cam=`echo $c | cut -d : -f 1`
    inp=`echo $c | cut -d : -f 2`
    #somagic-capture -n --sync=1 --iso-transfers=20 -i $inp -f $3 | ffmpeg -v quiet -f rawvideo -pix_fmt uyvy422 -s 720x480 -r ntsc -an -vf select="gte(n\,$ff)" -i pipe: -vf yadif -vtag 2vuy -aspect 1.77 -b:v 4000k -f image2 -pix_fmt bgr24 -s 320x240 -y -updatefirst 1 $2$cam-$buf.raw
    somagic-capture -n --sync=1 --iso-transfers=12 -i $inp -f $3 | ffmpeg -v quiet -f rawvideo -pix_fmt uyvy422 -s 720x480 -r ntsc -an -vf select="gte(n\,$ff)" -i pipe: -f image2 -pix_fmt bgr24 -s 320x240 -y -updatefirst 1 $2$cam-$buf.raw
    #don't remove the ,x after the next line!
    echo F,$cam,$cam-$buf.raw,320,240,x
  done
  (( buf++ ))
  if [ "$buf" -gt 4 ]; then
    buf=1
  fi
done
